# Generated by Django 2.2.3 on 2019-07-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=50)),
                ('type', models.CharField(default='', max_length=50)),
                ('desc', models.CharField(max_length=500)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
