# Generated by Django 2.2.3 on 2019-07-15 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20190715_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='pub_date',
        ),
    ]
